### ISSUE TITLE
I don't know where the configuration is wrong

### ISSUE THREAD

**Issue by leelax22** [alangrainger/share-note-self-hosted-backend#1]
I've configured php on the web server and tried it on Obsidian, but the error log isn't left in detail, so I can't get a clue where it's wrong. I'll try to explain what I've configured in as much detail as possible. I appreciate it if you can see if there's an error.

1. web server - apache2
```
<VirtualHost *:443>
    ServerName share.haramuko.site
    DocumentRoot /var/www/sharenote

    # 기본 DocumentRoot 디렉토리 설정
    <Directory /var/www/sharenote>
        Options FollowSymLinks
        Require all granted
        ExpiresActive On
        ExpiresDefault A600
    </Directory>

    # /api 경로를 /var/www/sharenote/api로 매핑
    Alias /api /var/www/sharenote/api

    <Directory /var/www/sharenote/api>
        Options FollowSymLinks
        Require all granted
        DirectoryIndex index.php
        ExpiresActive On
        ExpiresDefault A600
    </Directory>

    # /public 경로를 /var/www/sharenote/public으로 매핑
    Alias /public /var/www/sharenote/public

    <Directory /var/www/sharenote/public>
        Options FollowSymLinks
        Require all granted
        ExpiresActive On
        ExpiresDefault A600
    </Directory>

    SSLCertificateFile /etc/letsencrypt/live/haramuko.site-0002/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/haramuko.site-0002/privkey.pem
</VirtualHost>    
```

I made `test.php` in `/var/www/sharenote/api` and
`test.html` in `/var/www/sharenote/public`.

`https://share.haramuko.site/api/test.php`
`https://share.haramuko.site/public/test.html`
works on web. So I think web server setting is not wrong.

2. env.cfg
```
root@lcmvm3:/var/www/sharenote/api# cat env.cfg
[globals]
db_host=localhost
db_name=sharenote
db_user=sharenote
db_pass=qlalfqjsgh1
production=true
upload_folder=/var/www/sharenote/public
file_url_base=https://share.haramuko.site/public
assets_webroot=https://share.haramuko.site/public/assets
uid=****
private_key=****
```

I installed mysql and made database `sharenote` and assign all privilege to user `sharenote`
I don't see anything that could go wrong.

3. data.json
```
{
  "server": "https://share.haramuko.site/api",
  "uid": "****",
  "apiKey": "****",
  "yamlField": "share",
  "noteWidth": "",
  "theme": "",
  "themeMode": 0,
  "titleSource": 0,
  "removeYaml": true,
  "removeBacklinksFooter": true,
  "expiry": "",
  "clipboard": true,
  "shareUnencrypted": false,
  "authRedirect": "share",
  "debug": 0
}
```

In obsidan's data.json, parameters which should be changed are only server, uid, apiKey.
There doesn't seem to be anything to type incorrectly.

---
But, try to operate it after configuring it all, I got an error. (Of course, restarting several times)
![image](https://github.com/user-attachments/assets/067adeca-b481-46fd-818b-76bd9e51bb43)

```
[Thu Aug 01 10:16:49.376029 2024] [php:notice] [pid 223767] [client 123.141.145.22:11147] HTTP 404 (GET /)
[Thu Aug 01 10:16:49.376071 2024] [php:notice] [pid 223767] [client 123.141.145.22:11147] [api/f3/base.php:1829] Base->error()
[Thu Aug 01 10:16:49.376077 2024] [php:notice] [pid 223767] [client 123.141.145.22:11147] [api/index.php:29] Base->run()
```
I don't know if it's related, but when I access it on the web with `share.haramuko.site/api/`, I get 404 error.log in apache2, but php seems to have run, so I don't know if this is the intended action.

I can't find any clues even though I've searched several logs, so I'm asking for your help. 😓

**Comment by alangrainger** [comment]
Considering your web server is publicly facing, and you just posted your database user/password for the world to see, I strongly suggest you **do not self-host this**.

```
db_user=sharenote
db_pass=[redacted]
```

**Comment by leelax22** [comment]
Oh, that's right. But it's okay because it's impossible to access 3306 ports from outside due to cloud security anyway.

**Comment by leelax22** [comment]
Maybe your self-hosting concept is a little different from what I thought.

In fact, the reason I want to self-hosted web server is not because I can't trust you. I'm worried about a situation where your web server is stopped or the service is completely terminated.

Keeping notes on my computer and not being able to share them over the web is not what I want. If I just want to view them for myself, I don't need to use share note, I can just view them in read mode in obsidian.

I'm a little confused, so I'd like to hear other people's opinions. Thank you so much for your quick feedback. 🙏

**Comment by alangrainger** [comment]
This is not intended to run locally on your computer. The share notes `/public/` folder is intended to  be web-accessible.

However, based on your initial post having your credentials in it for the world to see, I am suggesting that you might want to reconsider self-hosting. It's not easy to make things secure.

**Comment by leelax22** [comment]
Then I'm glad I didn't misunderstand the concept of self-hosting itself. 
First of all, I wanted to see if it worked well, so I didn't have enough security. 
Anyone can access the env.cfg file, so values were exposed. I need to check the Apache settings and set it up to prevent access to important files.

Anyway, there seems to be no problem with the web server url configuration itself, is there a way to check more logs that can be a clue where the error comes from?

**Comment by alangrainger** [comment]
It sounds like your [.htaccess](https://github.com/alangrainger/share-note-self-hosted-backend/blob/main/api/.htaccess) is not working correctly. All API files should be re-written to `index.php`, so the fact that you can access `test.php` indicates your Apache rewrites aren't working.

**Comment by leelax22** [comment]
Thanks to your help, I succeeded about 90%. 🤗
I was not familiar with the fat-free framework, so I spent time wandering around thinking that if I enter an authorized account, it would automatically create a table. It doesn't.
I asked ChatGPT to create a table schema based on php file, after that I found that you provided the schema.sql file. 😂

![image](https://github.com/user-attachments/assets/6971f307-a507-48b2-9666-04ee3e1fd66f)

The only thing I can't solve is that when I share my notes, the URL came out like this
`https://share.haramuko.site/public/notes/ZXkXOPp5#AzAH3Qbbr7/Nw+H9K4r37j5C+10RBDLrsX+OffcrqJo`

To access url, I need to add '.html' like this
`https://share.haramuko.site/public/notes/ZXkXOPp5.html#AzAH3Qbbr7/Nw+H9K4r37j5C+10RBDLrsX+OffcrqJo`
I think it's because `.html` is missing from the URL delivered to POST delete api.

In apache2 log, 
```
[Fri Aug 02 16:15:14.807050 2024] [php:notice] [pid 247444] [client 123.141.145.22:64222] HTTP 404 (POST /v1/file/delete)
[Fri Aug 02 16:15:14.808970 2024] [php:notice] [pid 247444] [client 123.141.145.22:64222] [api/f3/base.php:1829] Base->error()
[Fri Aug 02 16:15:14.808983 2024] [php:notice] [pid 247444] [client 123.141.145.22:64222] [api/index.php:29] Base->run()
```

Would you mind checking that part, please?

**Comment by alangrainger** [comment]
Sorry for not mentioning the SQL schema in the docs, I will add that now.

This new issue is again because of your `.htaccess` configuration in Apache.

There's another [.htaccess file](https://github.com/alangrainger/share-note-self-hosted-backend/blob/main/public/.htaccess) in the `/public/` directory which adds the `.html` extension for you when a file is requested.

**Comment by leelax22** [comment]
You told me above HTAccess, but I forgot again stupidly. I applied htaccess setting to public folder.

And I miss one thing.
After I created table using your `schema.sql` but got error like this.
`[Fri Aug 02 17:31:01.865898 2024] [php:notice] [pid 249192] [client 123.141.145.22:9438] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'hash' in 'where clause' [/var/www/sharenote/api/f3/db/sql.php:230]`

Original Schema
```
CREATE TABLE `files` (
                         `id` int NOT NULL,
                         `users_id` int NOT NULL,
                         `filename` char(32) NOT NULL,
                         `filetype` varchar(10) NOT NULL,
                         `created` datetime NOT NULL,
                         `updated` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```


```
`hash` CHAR(40) NOT NULL UNIQUE
```

After I added `hash` column, it works. I don't know this is right solution.
Have a good weekend.🤗

**Comment by alangrainger** [comment]
Thanks for noticing the missing column - I have updated the schema now. You've added the right column :+1: 

I'm glad it's all working for you!

**Comment by 0xGitGuy** [comment]
> Thanks to your help, I succeeded about 90%. 🤗 I was not familiar with the fat-free framework, so I spent time wandering around thinking that if I enter an authorized account, it would automatically create a table. It doesn't. I asked ChatGPT to create a table schema based on php file, after that I found that you provided the schema.sql file. 😂
> 
> ![image](https://private-user-images.githubusercontent.com/49804063/354509357-6971f307-a507-48b2-9666-04ee3e1fd66f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNzE1MjQsIm5iZiI6MTcyNDE3MTIyNCwicGF0aCI6Ii80OTgwNDA2My8zNTQ1MDkzNTctNjk3MWYzMDctYTUwNy00OGIyLTk2NjYtMDRlZTNlMWZkNjZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDE2MjcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1YmNjZWJmMGZmMDY1OWZiMjdiOTZjMDBkMWY5MWUwZjU1ZDYxMTRhNDk3MmM1OGEzMzUzNDBmZTdhMTRhY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bWf6_EXfSoyGRm7QkIeYUxJNMHhZTNI23bw1sxtTdvI)
> 
> The only thing I can't solve is that when I share my notes, the URL came out like this `https://share.haramuko.site/public/notes/ZXkXOPp5#AzAH3Qbbr7/Nw+H9K4r37j5C+10RBDLrsX+OffcrqJo`
> 
> To access url, I need to add '.html' like this `https://share.haramuko.site/public/notes/ZXkXOPp5.html#AzAH3Qbbr7/Nw+H9K4r37j5C+10RBDLrsX+OffcrqJo` I think it's because `.html` is missing from the URL delivered to POST delete api.
> 
> In apache2 log,
> 
> ```
> [Fri Aug 02 16:15:14.807050 2024] [php:notice] [pid 247444] [client 123.141.145.22:64222] HTTP 404 (POST /v1/file/delete)
> [Fri Aug 02 16:15:14.808970 2024] [php:notice] [pid 247444] [client 123.141.145.22:64222] [api/f3/base.php:1829] Base->error()
> [Fri Aug 02 16:15:14.808983 2024] [php:notice] [pid 247444] [client 123.141.145.22:64222] [api/index.php:29] Base->run()
> ```
> 
> Would you mind checking that part, please?

What did you do to get to 90%? I'm using the current latest repo and server path is 

/var/www/html
/var/www/html/api
/var/www/html/public

left the .htaccess at where they were proposed as per repo

`[globals]
db_host=xxx.xxx.xxx.xxx
db_name=your_database_name
db_user=your_username
db_pass=your_pass
production=true
upload_folder=/var/www/public
file_url_base=xxx.xxx.xxx.xxx/public
assets_webroot=xxx.xxx.xxx.xxx/public/assets
uid=8a307375FAKEf249ce4381f10
private_key=e28616cde77FAKE64d0b9b27768a`

**Comment by alangrainger** [comment]
@0xGitGuy what's the issue you're experiencing?

**Comment by 0xGitGuy** [comment]
> @0xGitGuy what's the issue you're experiencing?

Using this in data.json, I "Copy shared link" in plugin but don't see any error in console. Just stuck at "Share Note" Processing attachments..."

`{
  "server": "xxx.xxx.xxx.xxx/www/api",
  "uid": "8a307375FAKE9ce4381f10",
  "apiKey": "e28616cdeFAKE9764d0b9b27768a",
  "yamlField": "share",
  "noteWidth": "",
  "theme": "",
  "themeMode": 0,
  "titleSource": 0,
  "removeYaml": true,
  "removeBacklinksFooter": true,
  "expiry": "",
  "clipboard": true,
  "shareUnencrypted": false,
  "authRedirect": null,
  "debug": 0
}`

If i add back the http like below, I get console error like so:

`Error: Unknown error
    at API.post (plugin:share-note:3482:17)
    at async API.processQueue (plugin:share-note:3534:17)
    at async Note.share (plugin:share-note:15060:26)
    at async SharePlugin.uploadNote (plugin:share-note:15515:9)
    at async SharePlugin.copyShareLink (plugin:share-note:15538:7)
    at async eval (plugin:share-note:15470:15)
`

`{
  "server": "http://xxx.xxx.xxx.xxx/www/api",
  "uid": "8a307375FAKE9ce4381f10",
  "apiKey": "e28616cdeFAKE9764d0b9b27768a",
  "yamlField": "share",
  "noteWidth": "",
  "theme": "",
  "themeMode": 0,
  "titleSource": 0,
  "removeYaml": true,
  "removeBacklinksFooter": true,
  "expiry": "",
  "clipboard": true,
  "shareUnencrypted": false,
  "authRedirect": null,
  "debug": 0
}`

**Comment by alangrainger** [comment]
You'll need to check the web server logs on your server to find out what's going on.

**Comment by 0xGitGuy** [comment]
> Owner

Nothing in apache2 error.log immediately after I Copy Shared Link. 

apache2 access.log shows this
`xxx.xxx.xxx.xxx - - [20/Aug/2024:19:55:09 +0000] "POST /www/api/v1/file/check-files HTTP/1.1" 404 493 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.5.8 Chrome/120.0.6099.283 Electron/28.2.3 Safari/537.36"`

What else might be helpful to look into?

**Comment by alangrainger** [comment]
> `check-files HTTP/1.1" 404`

I'm guessing the `404` could be worth looking into. Try using an API client like [Insomnia](https://insomnia.rest/) to debug your server config.

**Comment by 0xGitGuy** [comment]
did the same initial test like @leelax22 for the .php in /api/ and .html in /public/ and it's working with the test. test.php connects to the database.

my apache2 /etc/apache2/sites-available/share-note.conf adapted from @leelax22 :

`<VirtualHost *:80>
    ServerName localhost
    DocumentRoot /var/www/html

    # Basic DocumentRoot directory settings
    <Directory /var/www/html>
        Options FollowSymLinks
        Require all granted
        ExpiresActive On
        ExpiresDefault A600
    </Directory>

    # Map /api path to /var/www/sharenote/api
    Alias /api /var/www/html/api

    <Directory /var/www/html/api>
        Options FollowSymLinks
        Require all granted
        DirectoryIndex index.php
        ExpiresActive On
        ExpiresDefault A600
    </Directory>

    # Map /public path to /var/www/sharenote/public
    Alias /public /var/www/html/public

    <Directory /var/www/html/public>
        Options FollowSymLinks
        Require all granted
        ExpiresActive On
        ExpiresDefault A600
    </Directory>

    # Log files
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>`

data.json

`{
  "server": "http://xxx.xxx.xxx.xxx/api",
  "uid": "8a307375635FAKEf249ce4381f10",
  "apiKey": "e28616cde77FAKEd0b9b27768a",
  "yamlField": "share",
  "noteWidth": "",
  "theme": "",
  "themeMode": 0,
  "titleSource": 0,
  "removeYaml": true,
  "removeBacklinksFooter": true,
  "expiry": "",
  "clipboard": true,
  "shareUnencrypted": false,
  "authRedirect": null,
  "debug": 0
}`

env.cfg

`[globals]
db_host=localhost
db_name=your_database_name
db_user=your_username
db_pass=0AFKEFAKFAKEA
production=true
upload_folder=/var/www/html/public
file_url_base=http://xxx.xxx.xxx.xxx/public
assets_webroot=http://1xxx.xxx.xxx.xxx/public/assets
uid=8a30737560AFKEFAKFAKEA49ce4381f10
private_key=e28616cd0AFKEFAKFAKEA0b9b27768a`

Still can't figure out what's wrong. Obsidian plugin client still cant find the f3 route path and throwing 404

**Comment by alangrainger** [comment]
Then your `.htaccess` configuration is not working in Apache. You should **not** be able to access the test.php file.

**Comment by 0xGitGuy** [comment]
Thanks! I set AllowOverride from None to All and the .htaccess behaves as you described. I could generate the encrypted html and hash in database.

`<Directory /var/www/>
	Options Indexes FollowSymLinks
	AllowOverride All
	Require all granted
</Directory>`

However, when clicking on the link, it opens the webpage that says "Unable to decrypt using this key.". Like @leelax22, the link doesn't have the .html. Unlike him, despite appending the .html, it still shows "Unable to decrypt using this key." 

http://xxx.xxx.xxx.xxx/public/notes/mg6UBHHE#VW+lUWyj8B5QDcfCEDWLV2h1ws2QhgGTQaRoeMNtDQU
TO
http://xxx.xxx.xxx.xxx/public/notes/mg6UBHHE.html#VW+lUWyj8B5QDcfCEDWLV2h1ws2QhgGTQaRoeMNtDQU

I tested going to http://xxx.xxx.xxx.xxx/public/notes/test, it shows the test.html page which previously it didnt.
Going to http://xxx.xxx.xxx.xxx/api/test.php, it gives 404 which is intended as you described.

**Comment by 0xGitGuy** [comment]
I don't think my issue is because of htaccess anymore. When i share the unencrypted note, i was able to view fine. When accessing the encrypted note, despite the "Unable to decrypt using this key.", the page source codes shows the html was able to be access fine.

This leaves the problem to the decryption process that resulted in the encrypted note unviewable.

I'm not entirely familiar with the cryptography component. How does it work? What can i do to perform some basic test to isolate the decryption problem?

**Comment by alangrainger** [comment]
The encryption happens inside your Obsidian, it's nothing to do with the server. Try it in a Sandbox vault.

**Comment by 0xGitGuy** [comment]
In sandbox with just share-note plugin alone, same thing "Unable to decrypt using this key.". If i just use your hosted service, it decrypts just fine. 

Here's my testing 35 char keys:
  "uid": "34a93b8c7d5a78dc69d940898ee6c325",
  "apiKey": "0b683bed9eb3eceb786e3e18d7cf699a",

Seems like the user authentication failed when checked with apache logs:

``` [Thu Aug 22 19:23:13.892762 2024] [php:notice] [pid 75730] [client xxx.xxx:54335] HTTP 401 (POST /v1/file/check-files)
[Thu Aug 22 19:23:13.892797 2024] [php:notice] [pid 75730] [client xxx.xxx:54335] [api/classes/Controller.php:82] Base->error()
[Thu Aug 22 19:23:13.892800 2024] [php:notice] [pid 75730] [client xxx.xxx:54335] [api/classes/Controller.php:53] Controller->errorAndDie()
[Thu Aug 22 19:23:13.892803 2024] [php:notice] [pid 75730] [client xxx.xxx:54335] [api/classes/Controller.php:15] Controller->checkValidUser()
[Thu Aug 22 19:23:13.892805 2024] [php:notice] [pid 75730] [client xxx.xxx:54335] [api/classes/File.php:32] Controller->__construct()
[Thu Aug 22 19:23:13.892808 2024] [php:notice] [pid 75730] [client xxx.xxx:54335] [api/index.php:36] Base->run()
[Thu Aug 22 19:23:47.200380 2024] [php:notice] [pid 75734] [client xxx.xxx:54350] HTTP 401 (POST /v1/file/check-files)
[Thu Aug 22 19:23:47.200419 2024] [php:notice] [pid 75734] [client xxx.xxx:54350] [api/classes/Controller.php:82] Base->error()
[Thu Aug 22 19:23:47.200426 2024] [php:notice] [pid 75734] [client xxx.xxx:54350] [api/classes/Controller.php:70] Controller->errorAndDie()
[Thu Aug 22 19:23:47.200430 2024] [php:notice] [pid 75734] [client xxx.xxx:54350] [api/classes/Controller.php:15] Controller->checkValidUser()
[Thu Aug 22 19:23:47.200444 2024] [php:notice] [pid 75734] [client xxx.xxx:54350] [api/classes/File.php:32] Controller->__construct()
[Thu Aug 22 19:23:47.200448 2024] [php:notice] [pid 75734] [client xxx.xxx:54350] [api/index.php:36] Base->run()
[Thu Aug 22 19:24:02.414507 2024] [php:notice] [pid 75743] [client xxx.xxx:54356] HTTP 401 (POST /v1/file/check-files)
[Thu Aug 22 19:24:02.414532 2024] [php:notice] [pid 75743] [client xxx.xxx:54356] [api/classes/Controller.php:82] Base->error()
[Thu Aug 22 19:24:02.414536 2024] [php:notice] [pid 75743] [client xxx.xxx:54356] [api/classes/Controller.php:70] Controller->errorAndDie()
[Thu Aug 22 19:24:02.414539 2024] [php:notice] [pid 75743] [client xxx.xxx:54356] [api/classes/Controller.php:15] Controller->checkValidUser()
[Thu Aug 22 19:24:02.414541 2024] [php:notice] [pid 75743] [client xxx.xxx:54356] [api/classes/File.php:32] Controller->__construct()
[Thu Aug 22 19:24:02.414544 2024] [php:notice] [pid 75743] [client xxx.xxx:54356] [api/index.php:36]
[Thu Aug 22 19:50:52.693834 2024] [mpm_prefork:notice] [pid 80779] AH00170: caught SIGWINCH, shutting down gracefully
[Thu Aug 22 19:50:52.849659 2024] [mpm_prefork:notice] [pid 80861] AH00163: Apache/2.4.58 (Ubuntu) configured -- resuming normal operations
[Thu Aug 22 19:50:52.849713 2024] [core:notice] [pid 80861] AH00094: Command line: '/usr/sbin/apache2'
[Thu Aug 22 19:50:54.330878 2024] [php:error] [pid 80863] [client xxx.xxx:55221] script '/var/www/html/index.php' not found or unable to stat
[Thu Aug 22 19:50:54.974772 2024] [php:error] [pid 80863] [client xxx.xxx:55221] script '/var/www/html/index.php' not found or unable to stat
[Thu Aug 22 19:50:55.347682 2024] [php:error] [pid 80863] [client xxx.xxx:55221] script '/var/www/html/index.php' not found or unable to stat
[Thu Aug 22 19:50:58.678608 2024] [php:error] [pid 80864] [client xxx.xxx:55223] script '/var/www/html/index.php' not found or unable to stat
[Thu Aug 22 19:50:59.446570 2024] [php:error] [pid 80863] [client xxx.xxx:55221] script '/var/www/html/index.php' not found or unable to stat
[Thu Aug 22 19:51:00.756698 2024] [php:error] [pid 80863] [client xxx.xxx:55221] script '/var/www/html/index.php' not found or unable to stat
[Thu Aug 22 19:51:00.806550 2024] [php:error] [pid 80863] [client xxx.xxx:55221] script '/var/www/html/index.php' not found or unable to stat, referer: http://xxx.xxx/public/notes/NYBI6TiY
[Thu Aug 22 19:51:02.700674 2024] [php:error] [pid 80863] [client xxx.xxx:55221] script '/var/www/html/index.php' not found or unable to stat
[Thu Aug 22 19:51:02.738627 2024] [php:error] [pid 80863] [client xxx.xxx:55221] script '/var/www/html/index.php' not found or unable to stat, referer: http://xxx.xxx/public/notes/NYBI6TiY
[Thu Aug 22 19:51:15.531879 2024] [php:error] [pid 80865] [client xxx.xxx:55235] script '/var/www/html/index.php' not found or unable to stat
[Thu Aug 22 19:51:15.568600 2024] [php:error] [pid 80865] [client xxx.xxx:55235] script '/var/www/html/index.php' not found or unable to stat, referer: http://xxx.xxx/public/notes/NYBI6TiY
[Thu Aug 22 19:51:17.216023 2024] [mpm_prefork:notice] [pid 80861] AH00170: caught SIGWINCH, shutting down gracefully
[Thu Aug 22 19:51:17.349874 2024] [mpm_prefork:notice] [pid 80884] AH00163: Apache/2.4.58 (Ubuntu) configured -- resuming normal operations
[Thu Aug 22 19:51:17.349941 2024] [core:notice] [pid 80884] AH00094: Command line: '/usr/sbin/apache2'
[Thu Aug 22 19:52:14.986701 2024] [mpm_prefork:notice] [pid 80884] AH00170: caught SIGWINCH, shutting down gracefully
[Thu Aug 22 19:52:15.121865 2024] [mpm_prefork:notice] [pid 80905] AH00163: Apache/2.4.58 (Ubuntu) configured -- resuming normal operations
[Thu Aug 22 19:52:15.121940 2024] [core:notice] [pid 80905] AH00094: Command line: '/usr/sbin/apache2'
[Thu Aug 22 19:52:17.066071 2024] [php:error] [pid 80907] [client xxx.xxx:55271] script '/var/www/html/index.php' not
found or unable to stat, referer: http://xxx.xxx/public/notes/NYBI6TiY
[Thu Aug 22 19:52:17.493075 2024] [php:error] [pid 80907] [client xxx.xxx:55271] script '/var/www/html/index.php' not found or unable to stat, referer: http://xxx.xxx/public/notes/NYBI6TiY
[Thu Aug 22 19:52:17.864039 2024] [php:error] [pid 80907] [client xxx.xxx:55271] script '/var/www/html/index.php' not found or unable to stat, referer: http://xxx.xxx/public/notes/NYBI6TiY
[Thu Aug 22 19:52:19.435014 2024] [php:error] [pid 80907] [client xxx.xxx:55271] script '/var/www/html/index.php' not found or unable to stat, referer: http://xxx.xxx/public/notes/NYBI6TiY
[Thu Aug 22 19:52:19.751059 2024] [php:error] [pid 80907] [client xxx.xxx:55271] script '/var/www/html/index.php' not found or unable to stat, referer: http://xxx.xxx/public/notes/NYBI6TiY
[Thu Aug 22 19:52:20.242137 2024] [php:error] [pid 80907] [client xxx.xxx:55271] script '/var/www/html/index.php' not found or unable to stat, referer: http://xxx.xxx/public/notes/NYBI6TiY
[Thu Aug 22 19:52:44.006064 2024] [php:error] [pid 80916] [client xxx.xxx:55301] script '/var/www/html/index.php' not found or unable to stat, referer: http://xxx.xxx/public/notes/NYBI6TiY
[Thu Aug 22 19:52:44.155996 2024] [php:error] [pid 80916] [client xxx.xxx:55301] script '/var/www/html/index.php' not found or unable to stat, referer: http://xxx.xxx/public/notes/NYBI6TiY
[Thu Aug 22 19:57:20.611745 2024] [php:error] [pid 80922] [client xxx.xxx:55476] script '/var/www/html/index.php' not found or unable to stat, referer: http://xxx.xxx/public/notes/NYBI6TiY
[Thu Aug 22 20:06:09.225983 2024] [php:error] [pid 80913] [client xxx.xxx:47146] script '/var/www/html/index.php' not found or unable to stat
[Thu Aug 22 20:07:00.678070 2024] [php:notice] [pid 80912] [client xxx.xxx:55890] HTTP 404 (POST /v1/file/delete)
[Thu Aug 22 20:07:00.678105 2024] [php:notice] [pid 80912] [client xxx.xxx:55890] [api/index.php:36] Base->run()
[Thu Aug 22 20:09:28.270259 2024] [php:error] [pid 80909] [client xxx.xxx:55972] script '/var/www/html/index.php' not found or unable to stat, referer: http://xxx.xxx/public/notes/NYBI6TiY
[Thu Aug 22 20:09:30.719769 2024] [php:error] [pid 80909] [client xxx.xxx:55972] script '/var/www/html/index.php' not found or unable to stat, referer: http://xxx.xxx/public/notes/NYBI6TiY
```

**Comment by 0xGitGuy** [comment]
Tried matching my server time zone with my obsidian host time zone, thinking could be the nonce issue, didnt help.

Noticed despite the only user, each time i wipe the database and re-upload the encrypted notes, the db users_id always stays at 34. Happens to be the start of the uid.

**Comment by 0xGitGuy** [comment]
@alangrainger do you happen to have the server env requirement for this backend? Or if you ever make this into a docker, it will be so much better! Have been trying to debug the aes ciphertext for hours, not sure if i'm on the right path

**Comment by alangrainger** [comment]
I'm wondering if it's a problem with letter case in the URL? I pushed a change which will use only lowercase URLs, which you should pull down and test.

Otherwise I recommend to use the normal share.note.sx backend if you're having issues self-hosting.

**Comment by alangrainger** [comment]
What do you mean by server env requirement? Nothing special, just Apache, PHP, and MySQL. It's an very simple PHP app - I recommend to use the normal share.note.sx backend if it's causing this many issues.

**Comment by 0xGitGuy** [comment]
I wonder if the respective versions would cause any issues. Matching it the same as yours would rule this out.

**Comment by alangrainger** [comment]
I used the docker image `php:8.1-apache`
