### ISSUE TITLE
Write permission on /var/www/html/public/notes

### ISSUE THREAD

**Issue by pablocerdeira** [alangrainger/share-note-self-hosted-backend#10]
Error:
After stating the containers and configuring the Obsidian data.json, when you try to share a note it will work partially. The database records are created but no file is created under /var/www/html/public/notes due to a lack of permission to write on it:

Log:
sharenote-app-1  | 100.108.102.111 - - [29/Sep/2024:10:43:59 +0000] "GET / HTTP/1.1" 403 491 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Safari/605.1.15"
sharenote-app-1  | 100.108.102.111 - - [29/Sep/2024:10:44:10 +0000] "GET /api/v1/account/get-key HTTP/1.1" 200 768 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Safari/605.1.15"
sharenote-app-1  | 100.108.102.111 - - [29/Sep/2024:10:56:10 +0000] "POST /api/v1/file/check-files HTTP/1.1" 200 548 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.5.3 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36"
sharenote-app-1  | 100.108.102.111 - - [29/Sep/2024:10:56:10 +0000] "POST /api/v1/file/check-files HTTP/1.1" 200 5518 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.5.3 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36"
sharenote-app-1  | 100.108.102.111 - - [29/Sep/2024:10:56:10 +0000] "OPTIONS /api/v1/file/upload HTTP/1.1" 200 307 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.5.3 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36"
sharenote-app-1  | 100.108.102.111 - - [29/Sep/2024:10:56:10 +0000] "OPTIONS /api/v1/file/upload HTTP/1.1" 200 307 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.5.3 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36"
sharenote-app-1  | 100.108.102.111 - - [29/Sep/2024:10:56:10 +0000] "OPTIONS /api/v1/file/upload HTTP/1.1" 200 307 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.5.3 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36"
...
sharenote-app-1  | 100.108.102.111 - - [29/Sep/2024:10:56:11 +0000] "POST /api/v1/file/upload HTTP/1.1" 200 662 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.5.3 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36"
sharenote-app-1  | 100.108.102.111 - - [29/Sep/2024:10:56:11 +0000] "POST /api/v1/file/upload HTTP/1.1" 200 661 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.5.3 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36"
sharenote-app-1  | 100.108.102.111 - - [29/Sep/2024:10:56:11 +0000] "POST /api/v1/file/upload HTTP/1.1" 200 659 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.5.3 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36"
...
sharenote-app-1  | 100.108.102.111 - - [29/Sep/2024:10:56:12 +0000] "POST /api/v1/file/upload HTTP/1.1" 200 666 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.5.3 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36"
sharenote-app-1  | [Sun Sep 29 10:56:12.318626 2024] [php:notice] [pid 20:tid 20] [client 100.108.102.111:52138] file_put_contents(/var/www/html/public/notes/rrtqvxjf.html): Failed to open stream: Permission denied
sharenote-app-1  | [Sun Sep 29 10:56:12.318640 2024] [php:notice] [pid 20:tid 20] [client 100.108.102.111:52138] [api/classes/File.php:80]
sharenote-app-1  | [Sun Sep 29 10:56:12.318642 2024] [php:notice] [pid 20:tid 20] [client 100.108.102.111:52138] [api/classes/File.php:80] file_put_contents()
sharenote-app-1  | [Sun Sep 29 10:56:12.318644 2024] [php:notice] [pid 20:tid 20] [client 100.108.102.111:52138] [api/classes/File.php:235] File->saveFile()
sharenote-app-1  | [Sun Sep 29 10:56:12.318646 2024] [php:notice] [pid 20:tid 20] [client 100.108.102.111:52138] [api/index.php:37] Base->run()

Fix:
You need to change de Dockerfile to create and set the folder permissions.

Replace:
# Set permissions
RUN chown -R www-data:www-data /var/www/html

By:
# Create the 'public/notes' directory and set permissions
RUN mkdir -p /var/www/html/public/notes && \
    chown -R www-data:www-data /var/www/html && \
    chmod -R 775 /var/www/html/public/notes
    
Recreate the containers and it should work.

**Comment by pablocerdeira** [comment]
This project is amazing! Congrats!

I'll try the https://github.com/tannercollin/sharenote-py

Am I correct to assume this one will be replaced but the Python version? If so, I think the encryption is a must have, as I have some notes I'd like to share with a group of people but I don't want to leave it open to the web.

Best e congratulations!

**Comment by alangrainger** [comment]
> Am I correct to assume this one will be replaced but the Python version? If so, I think the encryption is a must have

My only focus is on the https://share.note.sx version, which includes encryption. Both the Python version above and the Docker version were not created by me. 

I can say that the non-Docker PHP version does functional perfectly and includes encryption. The folders you're needing to be created should be getting created when the file is saved (and I can confirm this happens in my test environment):

https://github.com/alangrainger/share-note-self-hosted-backend/blob/main/api/classes/File.php#L77-L79

I couldn't comment on Docker permissions sorry as that's outside my wheelhouse.
