### ISSUE TITLE
Is the handling of the api endpoint secure?!

### ISSUE THREAD

**Issue by izosozi** [alangrainger/share-note-self-hosted-backend#13]
> 1. Copy ./api/env.cfg.example to ./api/env.cfg, and update with your specific configuration as below.
> 2. Point your API web root to the ./api/ folder in this repo.

It looks to me like ./api contains env.cfg, and env.cfg contains a username, password, and private key, and then ./api is being made publicly accessible on the web.

Maybe I'm missing something (I won't pretend to understand PHP, and I haven't yet tested this), but doesn't that mean the **server secrets will be publicly accessible** at https://mydomain.com/api/env.cfg?

If this is already accounted for, or if it is assumed the installer will protect these secrets in their server config, it would be wise to say so explicitly in the README.

**Comment by alangrainger** [comment]
The [.htaccess file](https://github.com/alangrainger/share-note-self-hosted-backend/blob/main/api/.htaccess) rewrites all requests to `index.php`, therefore if those files are accessible you need to properly configure your Apache to use the .htaccess file

**Comment by izosozi** [comment]
Thanks for the fast reply! That makes sense. I'm using nginx, but I've done something similar before so shouldn't be an issue.
