### ISSUE TITLE
Can't delete note

### ISSUE THREAD

**Issue by nicosomb** [alangrainger/share-note-self-hosted-backend#2]
Hello! Thank you so much for your great job. 

I installed my own web server (via nginx) and all is almost perfect ... but I can't delete a single note. 

Here is the error:

```
2024/08/27 18:24:19 [error] 738945#738945: *17473769 FastCGI sent in stderr: "PHP message: HTTP 404 (POST /v1/file/delete); PHP message: [index.php:36] Base->run()" while reading response header from upstream, client: 2a01:e0a:a75:24b0:d50f:1703:6e42:7edc, server: myserver.com, request: "POST /v1/file/delete HTTP/2.0", upstream: "fastcgi://unix:/run/php/php8.2-fpm.sock:", host: "myserver.com"
```

What is wrong on my side?

**Comment by alangrainger** [comment]
The delete note route didn't exist. I've added it now so you can pull down the update.

**Comment by nicosomb** [comment]
Thank you. 

The server available on this repository is not the same than your hosted version?

**Comment by alangrainger** [comment]
Normal backend uses only cloud services. I wrote this backend just for people who wanted to self host.
