### ISSUE TITLE
Request: docker and docker compose file

### ISSUE THREAD

**Issue by moh-slimani** [alangrainger/share-note-self-hosted-backend#4]
it would be amazing if you can provide docker composer file for quick self hosting in tools like Portainer CE

**Comment by alangrainger** [comment]
If you can submit a PR with that, it would be amazing :) I haven't made a Docker container before so I'm not really sure what the process is for doing that.

**Comment by uPagge** [comment]
Eh, that really wouldn't hurt :) I'll try to figure out how to do that, but I can't promise anything

**Comment by alangrainger** [comment]
Docker support has been added by @tristandb - thank you so much for that.

To use, pull the updated repo and follow the instructions in the readme.
