### ISSUE TITLE
I can't get it running | Selfhost

### ISSUE THREAD

**Issue by 20Bosko07** [alangrainger/share-note-self-hosted-backend#7]
Hi there!
I've been trying to self host this but I can't get it to work properly. DB and PHP seem to be working, but I can't upload anything. (Getting error) The API keys are correct and the same as in the config. (Running in Docker)
Can anyone help me?

**Comment by alangrainger** [comment]
Is it your `.htaccess`? So far every single issue has been people not setting their htaccess up correctly.

**Comment by 20Bosko07** [comment]
hey, thank you for helping.
I'am getting this error:
![image](https://github.com/user-attachments/assets/4ccad587-7cab-49cf-8f81-a183c39ca5c1)

**Comment by alangrainger** [comment]
Yep, so you need to set up your htaccess. L

**Comment by 20Bosko07** [comment]
Hey Hey!
I made some progress.
Now I'am getting this error:
<img width="1027" alt="image" src="https://github.com/user-attachments/assets/ad88b67c-41cc-4e36-a910-8cb557d748c8">


The config looks like this:
<img width="1027" alt="image" src="https://github.com/user-attachments/assets/944b02fb-7aa1-4eb7-b298-fc86b326eac1">
uid and privekey are filled with the same as in the plugin (with a good key)

can you helb me ?

**Comment by alangrainger** [comment]
That means you're good to go. What happens if you try to share a file?

**Comment by 20Bosko07** [comment]
Then I get a instant Message on the top right corner.

**Comment by alangrainger** [comment]
Maybe try the Docker container to test?

https://github.com/alangrainger/share-note-self-hosted-backend?tab=readme-ov-file#docker-compose-setup

**Comment by 20Bosko07** [comment]
Yes, it's running on Docker Compose.

**Comment by 20Bosko07** [comment]
@alangrainger do I have somewhere logs?

**Comment by alangrainger** [comment]
There's now a new Python self-hosted backend - you can give this one a go:

https://github.com/tannercollin/sharenote-py

**Comment by 20Bosko07** [comment]
Hey @alangrainger
Somehow now uploading a note is working. 1. The link it generates is always localhost, but this is not a big problem. 2. When I open up the link I get:
Not Found
The requested URL was not found on this server.

Apache/2.4.62 (Debian) Server at 192.168.0.103 Port 80

Do you have any Ideas?
